### ISSUE TITLE
Custom logger function

### ISSUE THREAD

**Issue by bradisbell** [jspizziri/sequelize-singleton#1]
Thanks for putting this together.  This is a helpful library.

I have an enhancement request.  Can you allow `db.logger` to be a function?  That way a custom logging function could be passed in rather than `console.log`, just like Sequelize.

**Comment by jspizziri** [comment]
Great idea. I've just released a new update that will do this for you: [v0.2.3](https://github.com/jspizziri/sequelize-singleton/releases/tag/v0.2.3) via https://github.com/jspizziri/sequelize-singleton/commit/4cf1b02dbb4f5b24e5917ad97378b300c5efa3b4
