### ISSUE TITLE
Accessing models

### ISSUE THREAD

**Issue by shaoner** [jspizziri/sequelize-singleton#3]
``` javascript
// somefile.js

var orm       = require('sequelize-singleton');
var sequelize = orm.sequelize;
var Sequelize = orm.Sequelize;
var models    = orm.models;
var User      = models.User;
```

In your example, you seem to be able to retrieve a model from anywhere.
However, if you do that while _connect_ has not been called already, then you're screwed because your _models_ variable will be empty at first.
This means you cannot require your singleton and get your models if it's not already connected.

**Comment by jspizziri** [comment]
That's correct, as models are discovered and built on `connect`. Typically you would want to call connect when you app is initialized, like in `app.js` for instance. In the example code above, it is assumed that `connect` has already been called. I suppose I could make that a little clearer in the documentation.

The reason the behind this is that Models need to be defined in the context of a `Sequelize` instance (by calling `sequelize.define()`), which you cannot have without connecting.

Ex.

``` js
 var Model = sequelize.define("Model", {
    value:  DataTypes.INTEGER
  }, {
    underscored:  true,
    paranoid:     true,
    tableName:    'model',
    classMethods : {
      associate: function(models){
        Model.hasMany(models.OtherModel, { through: 'model_other_model'});
      }
    }
);
```

Effectively you don't have a model without having a `sequelize` instance.

Does that make sense? Or am I missing something.

**Comment by jspizziri** [comment]
I've added a note to the documentation here: https://github.com/jspizziri/sequelize-singleton#configuring-sequelize-singleton

**Comment by shaoner** [comment]
Oh actually I was just confused because of the way Mongoose works.
I thought you meant to do this at the **top** of each file that needs a model

``` javascript
var User = models.User;
```

This would of course be a big constraint to ensure that your file is loaded only after the connection has been established.

I ended up writing a model wrapper which is completely agnostic to the _Sequelize_ instance during its definition.

**Comment by jspizziri** [comment]
If I'm not mistaken mongoose also needs to be"connected" upon app initialization.

Also, that's interesting, would you mind providing an example of the wrapper or at least an abstraction of its interface?

**Comment by shaoner** [comment]
No, mongoose doesn't need to be connected during the definition of the model. It only needs a connection when using the model, so you are able to require a model prior to mongoose connection:

``` javascript
var UserSchema = mongoose.Schema({ /* ... */ });
var User = mongoose.model('User', UserSchema);
/* 
 * Here nothing is connected yet and 
 * this is fine as long as I don't use User methods that need a connection
 * mongoose.model only register the schema for when the connection will be opened
*/
mongoose.connect(/* ... */);
/* Now I'm able to call User.find(...) */
```

About the wrapper, it's more like a schema wrapper actually so it's not that interesting it just allows me to retrieve all models from anywhere without taking care of require ordering, but just like `orm.models` in your example.

If you include `orm.models` everywhere it is fine to retrieve your models from there, it can be filled after the _require_ statement.

Here is a simplified version of the schema wrapper:

``` javascript
'use strict';

var Sequelize = require('sequelize');
var _ = require('lodash');
var Schema = function (name, core, association, options) {
    if (!(this instanceof Model)){
        return new Model(name, core, association, options);
    }
    options = options || { };
    this._name = name;
    this._core = core;
    this._options = _.defaults(options, {
        /* my default options here */
        timestamps: false,
        underscored: true,
        underscoredAll: true,
        freezeTableName: true,
        classMethods: { },
        instanceMethods: { },
        hooks: { }
    });
    this._association = association;
};

Object.defineProperty(Schema.prototype, 'statics', {
    get: function () { return this._options.classMethods; }
});

Object.defineProperty(Schema.prototype, 'methods', {
    get: function () { return this._options.instanceMethods; }
});

Object.defineProperty(Schema.prototype, 'hooks', {
    get: function () { return this._options.hooks; }
});

Schema.Type = Sequelize;
```

So I am able to define my models like this:

``` javascript
'use strict';

var Schema = require('./schema');
var T = Schema.Type;
var $ = require('./models');

var User = Schema('User', {
    emailAddress: { type: T.STRING(255),  allowNull: false, unique: true },
    password: { type: T.STRING(255), allowNull: false },
    username: { type: T.STRING(50), unique: true },
}, function ($) {
    /* this is executed after all models have been loaded */
    this.hasOne($.Avatar);
});

User.statics.register = function (email, password) {
/* this.create(...) or $.User.create(...) */
};

User.methods.getProfile = function () {
    return { this.username };
};

module.exports = User;
```

`$` variable is actually a map of models that is filled at startup, just like `orm.models`:

``` javascript
Db.prototype.load = function(schemaDir) {
    var self = this;
    var sequelize = this.sequelize;
    var schema;
    fs.readdirSync(schemaDir).forEach(function(name) {
        schema = require(path.join(schemaDir, name));
        if (schema instanceof Schema) {
            // Create the sequelize model and store it in $
            $[schema._name] = sequelize.define(schema._name,
                                              schema._core,
                                              schema._options);
            self.schemas.push(schema);
        }
    });
    // Add associations
    this.schemas.forEach(function (schema) {
        if (_.isFunction(schema._association)) {
            schema._association.apply($[schema._name], [ $ ]);
        }
    });
};
```

So now, I'm able to retrieve models the same way using:

``` javascript
var $ = require('./models');
/* Here it may be empty */

router.get('/', function (req, res) {
   /* 
    * Here I'm sure $ contains all models
    * because I made it a requirement for the application to start 
   */
   $.User.find(/* ... *).then(/*... */);
});
```

To make it just like mongoose, we could imagine setting a sequelize attribute to the Schema wrapper after the connection has been established, and binding the sequelize methods to it as well:

``` javascript
Object.defineProperty(Schema.prototype, 'find', {
    get: function () {
     if (!this._seqmodel) { throw new Error('connection is not opened yet'); }
     return this._seqmodel.find;
});
```

User would be an instance of Schema or Model bound to a sequelize model under the hood, so you would only be able to use these methods after the connection has been established.
