### ISSUE TITLE
Peer sequelize-singleton@0.2.4 wants sequelize@~2.0

### ISSUE THREAD

**Issue by tashrafy** [jspizziri/sequelize-singleton#4]
Hi jspizziri,

Is it possible you can change your package.json to include all versions of sequelize >= 2.0?  I'd like to give this a package a try with more recent versions of sequelize.  This is the error I receive when trying to install sequelize-singleton with sequelize@3.3.2:

```
npm ERR! peerinvalid The package sequelize does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer sequelize-singleton@0.2.4 wants sequelize@~2.0
```

If possible, please update the peerDependencies in your package.json:

```
"peerDependencies": {
    "sequelize": ">=2.0"
},
```

**Comment by alexbooker** [comment]
I second this.

**Comment by jspizziri** [comment]
Sorry guys! Somehow I missed this issue.

**Comment by albertcui** [comment]
Could you push the update to npm? Thanks!

**Comment by jspizziri** [comment]
Updated, see [v0.2.5](https://github.com/jspizziri/sequelize-singleton/releases/tag/v0.2.5)
