### ISSUE TITLE
dive issue

### ISSUE THREAD

**Issue by ladeiko** [jspizziri/sequelize-singleton#8]
i think, dive have error:

dive(path, action); // Dive into the directory -> dive(path, action, matcher); // Dive into the directory

**Comment by jspizziri** [comment]
Can you attach the error please?

**Comment by jspizziri** [comment]
@ladeiko, I've fixed this https://github.com/jspizziri/sequelize-singleton/commit/f5527986efabfeb22e4df84aae848d85f328d57c. Feel free to submit a PR next time for the fix.
